# playbook.yml
---
- name: Simple nginx installation on vm's
  hosts: web
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create directory for website
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy website files
      copy:
        src: /home/chupin/course-hw/index.html
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
        directory_mode: '0755'

    - name: Copy nginx configuration
      copy:
        src: /home/chupin/course-hw/nginx.conf
        dest: /etc/nginx/sites-available/default
        backup: yes
      notify: restart nginx


    - name: Start and enable nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
